### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select

### ISSUE THREAD

**Issue by pillow-xi** [qiyuan-chen/Yaya-Moss-Alpaca-LoRA#3]
在model.generate()函数中报错请问应该如何修改
def evaluate(instruction, input=None):
    prompt = generate_prompt(instruction, input)
    inputs = tokenizer(prompt, return_tensors="pt")
    input_ids = inputs["input_ids"].cuda()
    print(input_ids)

    generation_output = model.generate(input_ids=input_ids,
                                       generation_config=generation_config,
                                       return_dict_in_generate=True,
                                       output_scores=True,
                                       max_new_tokens=256)
    
    for s in generation_output.sequences:
        output = tokenizer.decode(s)
        print("Response:", output.split("### Response:")[1].strip())

**Comment by qiyuan-chen** [comment]
这个问题是说明模型和数据不在一个设备上，请确保模型和数据都在GPU上
